FROM node:20

# tini - for passing SIGINT interrupts
ENV TINI_VERSION v0.19.0
ENV TINI_SUBREAPER true
ADD https://github.com/krallin/tini/releases/download/$TINI_VERSION/tini /tini
RUN chmod +x /tini
ENTRYPOINT ["/tini", "--"]

# dependencies
COPY package*.json .
RUN npm install

# source
COPY src/ src/
COPY config.json .
COPY tsconfig.build.json .
COPY tsconfig.json .
COPY nest-cli.json .
COPY *setups.json .
COPY .env.local .
RUN npm run build

CMD [ "node", "dist/main.js"]